language: node_js
node_js:
  - stable

branches:
  except:
    - dev

install:
  - npm install

script:
  - npm run lint
  - npm run unit
  - npm run component

after_success:
  - npm run coveralls
    if: branch = master

notifications:
  email: false